services:
  mysql:
    image: mysql:8.0
    container_name: loan-management-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loan_management
    ports:
      - "3306:3306"
    volumes:
      - loan_mysql_data:/var/lib/mysql

volumes:
  loan_mysql_data: